---
- name: Install epel yum repository
  yum:
    name: epel-release
    state: installed

- name: Install nginx
  yum:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy over index.html
  copy:
    src: ../files/index.html
    dest: /usr/share/nginx/html/index.html
  register: indexhtml
- name: restart nginx
  service: name=nginx state=restarted
  when: indexhtml.changed